### PR TITLE
[TTAHUB-1977] Change urls for training reports

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

Given a smartsheet provided ID for a training report, update training report urls to be /training-report/XXXX where X is the trailing numbers of that smartsheet ID. (Example: R01-TR-1234 would have a URL of /training-report/1234)

Also update session URLs to match: session with a DB id of 300 would have a URL of /training-report/1234/session/300

## How to test

- Ensure all CRUD operations for the training and session reports still work
- Inspect the database to confirm that no additional reports are being created
- Verify the URLs conform to the new design

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1977

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by thewatermethod** [comment]
Closing as someone else is taking this on

**Comment by thewatermethod** [comment]
Reopening as it was wishful thinking before

**Review by AdamAdHocTeam — COMMENTED** [review]
Delete session for me throws a 500 when there are files attached.

image

**Review by AdamAdHocTeam — COMMENTED** [review]
Another potential issue.

If I paste the following into the URL I'm noticing a majority of the summary info is missing. The session report is currently in progress and shows fine if I use the edit button.

Paste this with valid event and session id:
http://localhost:3000/training-report/1037/session/29

image

via edit button: 

image

**Comment by thewatermethod** [comment]
@AdamAdHocTeam those bugs (pretty sure both pre-exist this PR) are now fixed

**Review by AdamAdHocTeam — APPROVED** [review]
My issues have been fixed and looks good overall.

Might want one more review before merging but up to you.

**Review by GarrettEHill — APPROVED** [review]

**Pull request merged**
