### PR TITLE
[TTAHUB-2241] Update target populations

### PR DESCRIPTION
**Pull request by AdamAdHocTeam**
## Description of change

This adds, renames, and sorts the target populations on both the AR and TR.

Please see the JIRA ticket for a complete list of changes:
https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2241

In addition this fixes the JSON arrays in the 'EventReportPilots' table 'data' column to be correct arrays (with help from @GarrettEHill). 

## How to test

**Note:** You might need to run yarn deps to get latest common changes.

1. Review all changes.
2. Run the below queries before hand.
3. Run the migration.
4. Run the queries after (should be blank).
5. Create or edit a AR and TR change the reasons and target populations (verify updated and new values).
6. Verify TR shows the correct sort order (frequently used at the top).
7. Check the filters on all relevant pages make sure it reflects updates and filters.

**Queries to test:**

```
-- AR
SELECT id, "targetPopulations" FROM "ActivityReports" WHERE "targetPopulations" @> ARRAY['Preschool (ages 3-5)']::varchar[];
SELECT id, "targetPopulations" FROM "ActivityReports" WHERE "targetPopulations" @> ARRAY['Pregnant Women']::varchar[];
-- TR
SELECT data->>'targetPopulations' FROM "EventReportPilots" WHERE data->'targetPopulations' @> '"Preschool (ages 3-5)"';
SELECT data->>'targetPopulations' FROM "EventReportPilots" WHERE data->'targetPopulations' @> '"Pregnant Women/Pregnant People"';
```

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2241

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [x] Update JIRA ticket status

### CODE REVIEW

**Comment by thewatermethod** [comment]
Before migration:
Screenshot 2023-11-02 at 3 44 15 PM

After migration:
Screenshot 2023-11-02 at 3 45 13 PM

Same TR. Is that expected?

**Review by GarrettEHill — APPROVED** [review]

**Review by GarrettEHill — APPROVED** [review]

**Comment by AdamAdHocTeam** [comment]
> Before migration: Screenshot 2023-11-02 at 3 44 15 PM
> 
> After migration: Screenshot 2023-11-02 at 3 45 13 PM
> 
> Same TR. Is that expected?

@thewatermethod can you please test your use case again.

**Comment by thewatermethod** [comment]
Still having issues

Screenshot 2023-11-03 at 3 27 33 PM

Screenshot 2023-11-03 at 3 28 35 PM

**Review by thewatermethod — CHANGES_REQUESTED** [review]
see before and after screenshot, requesting changes just so there's no chance of accidental merge

**Comment by AdamAdHocTeam** [comment]
> see before and after screenshot, requesting changes just so there's no chance of accidental merge

In you latest issue we would have two tgt populations that would resolve to the same new value. The latest change removes duplicates after the clean up and transform.

**Comment by AdamAdHocTeam** [comment]
> According to the Jira "Children in Migrant and Seasonal Families" should appear on both the AR and the TR

@thewatermethod this should be good to go.

**Review by thewatermethod — APPROVED** [review]

**Pull request merged**
