### PR TITLE
[TTAHUB-1322] Change page title for goals and objectives page

### PR DESCRIPTION
**Pull request by GarrettEHill**
## Description of change
To keep consistency and fix google analytics page title needs to include recipient name. 

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1322

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by AdamAdHocTeam — APPROVED** [review]
Change seems to work. Although its not really made clear why we need this change? 🤷

**Comment by kryswisnaskas** [comment]
Thanks! 👍 

Could we also add/modify tests for it? Unit or end-to-end, if not both.

**Review by thewatermethod — APPROVED** [review]
Looks good - besides adding the test, we should also note (for future fixes)
- the error you got in the jira when trying to access the page as something that should be fixed
- we need to add a distinct page title for the "view/edit goals page"

**Comment by GarrettEHill** [comment]
> Looks good - besides adding the test, we should also note (for future fixes)
> 
> * the error you got in the jira when trying to access the page as something that should be fixed
> * we need to add a distinct page title for the "view/edit goals page"

do either of these need to be fixed in this jira, maybe the other page title?

**Comment by thewatermethod** [comment]
> do either of these need to be fixed in this jira, maybe the other page title?

Up to you  - the other page title should be as simple as this one but I don't want to expand the scope and delay this. If not doing those, maybe you could record them as their own Jiras?

**Review by kryswisnaskas — APPROVED** [review]
👍

**Pull request merged**
