### PR TITLE
Hook up phrase matching with limit

### PR DESCRIPTION
**Pull request by AdamAdHocTeam**
## Description of change

Per Patrice we can keep phrase matching and limit results (2k).

## How to test

Searching for phrase like "lead water" should only return reports that contain those terms in that order.

Searching for a single word like 'water' will use a wild card match to find anything that contains 'water'.

We need to make sure that staging no longer hangs and returns only 2k results.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-0

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by thewatermethod** [comment]
Searching "eclkc.ohs.acf.hhs.gov/" returns nothing, whereas searching "eclkc.ohs.acf.hhs.gov" returns 2001 results (most of which contain the trailing slash, so I'm not sure the wildcard works the way you want it. Everything else looks good.

**Comment by AdamAdHocTeam** [comment]
> eclkc.ohs.acf.hh

If I search 

> Searching "eclkc.ohs.acf.hhs.gov/" returns nothing, whereas searching "eclkc.ohs.acf.hhs.gov" returns 2001 results (most of which contain the trailing slash, so I'm not sure the wildcard works the way you want it. Everything else looks good.

If I search eclkc.ohs.acf.hhs or eclkc I get the correct matches. This might just have to be something we change later.

**Comment by thewatermethod** [comment]
I'll approve this then to unblock you.
Can you log a ticket noting that searching by a full url returns no results?

**Comment by AdamAdHocTeam** [comment]
> I also saw something odd with the resources filter. The first 2 results are suspect.
> 
> `eclkc.ohs.acf.hhs.gov\/ - 10 ARs` eclkc.ohs.acf.hhs.gov - 472 ARs eclkc.ohs.acf.hhs.gov/ - 0 ARs "eclkc.ohs.acf.hhs.gov" - 2001 ARs "eclkc.ohs.acf.hhs.gov/" - 2001 ARs

You shouldn't need the quotes unless you want spaced before and after the word.

Lets go over your cases.

**Comment by kryswisnaskas** [comment]
> > I also saw something odd with the resources filter. The first 2 results are suspect.
> > `eclkc.ohs.acf.hhs.gov\/ - 10 ARs` eclkc.ohs.acf.hhs.gov - 472 ARs eclkc.ohs.acf.hhs.gov/ - 0 ARs "eclkc.ohs.acf.hhs.gov" - 2001 ARs "eclkc.ohs.acf.hhs.gov/" - 2001 ARs
> 
> You shouldn't need the quotes unless you want spaced before and after the word.
> 
> Lets go over your cases.

Once on Dev we can look at them and see if they are the same.

**Review by kryswisnaskas — APPROVED** [review]

**Review by thewatermethod — APPROVED** [review]

**Pull request merged**
