### PR TITLE
[TTAHUB-1828] Change all "GROUP BY TRUE" to "GROUP BY 1=1" to support postgres 15.x

### PR DESCRIPTION
**Pull request by GarrettEHill**
## Description of change
Postgres 15 does not like "GROUP BY  TRUE"
https://postgrespro.com/list/thread-id/2661353
work around is to use 1=1 in place of true

Include change to move postgres from 12.4 to 15.4

## How to test
tests work, can create a report

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1828

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by GarrettEHill** [comment]
@kcirtapfromspace can you look at this

**Comment by kcirtapfromspace** [comment]
@GarrettEHill How do you feel about this comment in that thread?

> Sure, you can write any constant expression, for instance NULL::bool
would work.  The question is where do we draw the line between SQL92
and SQL99 behaviors.  I think "an undecorated constant is SQL92, and
therefore it must be an integer matching an output column number" is
a nice simple rule.  The fact that TRUE and FALSE were not previously
treated as undecorated constants is an unintentional wart of the old
implementation, not something we ought to preserve.

I guess the conversation in there leans towards not maintaining support for  group by true this going forward. I'm curious if 1=1 is an obscure format that isn't really covered in the documentation. What alternatives might be used?

**Comment by thewatermethod** [comment]
@GarrettEHill did you say yesterday Angela had found an issue with testing this?

**Comment by GarrettEHill** [comment]
> @GarrettEHill did you say yesterday Angela had found an issue with testing this?

The issue was not with this, but a bug on resource dashboard

**Review by thewatermethod — APPROVED** [review]
Tested locally, and on dev. Runs on CI.

**Pull request merged**
