### PR TITLE
[TTAHUB-3533] Non monitoring grant warning

### PR DESCRIPTION
**Pull request by AdamAdHocTeam**
## Description of change

This displays an alert on the Goals and Objectives page of the AR when one or more of the grants selected doesn't have an associated monitoring goal.

image

## How to test

- Review the code
- Make sure the alert shows correctly with the appropriate text
- Make sure the alert isnt showing when it shouldn't
- Make sure the alert goes away when its no longer valid

## Issue(s)

* https://jira.acf.gov/browse/TTAHUB-3533

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete
- [ ] QA review complete

### Before merge to main

- [ ] OHS demo complete
- [ ] Ready to create production PR

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [x] Update JIRA ticket status

### CODE REVIEW

**Comment by thewatermethod** [comment]
I've only looked at the code but I don't think this meets the AC.

From the Jira:

When the OHS standard monitoring goal is the **only goal** on the activity report, do all grants listed in the AR summary have the goal? Invalid if: One or more grants does NOT have the OHS standard monitoring goal.

Correct me if I'm wrong but this just shows if you have a monitoring goal and a grant without a monitoring goal, it doesn't check if we have other goals, which is the case this is meant to solve.

**Comment by thewatermethod** [comment]
It also seems to be missing this AC:

_If the user does not correct the warning issues, they will get a similar error alert on submission of the report, and cannot proceed until they make the correction._

**Comment by AdamAdHocTeam** [comment]
> It also seems to be missing this AC:
> 
> _If the user does not correct the warning issues, they will get a similar error alert on submission of the report, and cannot proceed until they make the correction._

I thought that was this ticket: https://jira.acf.gov/browse/TTAHUB-3627

**Comment by thewatermethod** [comment]
> I thought that was this ticket: https://jira.acf.gov/browse/TTAHUB-3627

According to the AC at least, these two tickets are are validating different cases

**Comment by thewatermethod** [comment]
Screenshot 2024-12-16 at 9 18 49 AM

This report has two grants; one has the goal, one does not, but the alert lists them both

**Comment by thewatermethod** [comment]
> So I think this is correct you are seeing it because they have no matching citation's with that grant id.

Are you sure that is how it is supposed to work? Reading the language of the alert, I think the check is supposed to be see whether the grants have the monitoring goal

**Comment by AdamAdHocTeam** [comment]
> > So I think this is correct you are seeing it because they have no matching citation's with that grant id.
> 
> Are you sure that is how it is supposed to work? Reading the language of the alert, I think the check is supposed to be see whether the grants have the monitoring goal

Right now its a combo of both things:
1. must have a monitoring goal with the linked template
2. must have valid citations

**Review by thewatermethod — APPROVED** [review]

**Review by thewatermethod — APPROVED** [review]

**Pull request merged**
