### PR TITLE
[TTAHUB-1130] Orphaned goal cleanup

### PR DESCRIPTION
**Pull request by AdamAdHocTeam**
## Description of change

This PR does two things:
- Adds a script to cleanup orphan goals and objectives along with associated tables.
- Deletes goals created via AR if they are not being used.

## How to test
- Review all code and SQL.
- Run the migration make sure it competes successfully. 
**NOTE:** A script Garrett wrote should give you an idea of what we can expect to be deleted on the JIRA TTAHUB-1130.
- Create a goal on a report and remove the Goal from the report and save. The goal should be removed from the DB.
- Create a goal on another report then use the same goal on a new report and remove it and save. The goal should NOT be removed from the db.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1130

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [x] Update JIRA ticket status

### CODE REVIEW

**Comment by GarrettEHill** [comment]
The counts I supplied are the valid numbers for all the records that should be deleted based on the corresponding goals being deleted.

The numbers match what this implementation achieves with the exception of Resources and Files, where your numbers are 7 and 8 higher respectively. This difference are the orphan records within those tables, specifically the additional resources and files that are being deleted are not linked to any other records prior to that execution of the cleanup script. While this is good to get cleaned up, it highlights a gap in the implemented logic of the site and this migration. We need to try to prevent unexpectedly deleting records from any tables.

**Review by GarrettEHill — APPROVED** [review]

**Comment by GarrettEHill** [comment]
Please write JIRAs for the two unexpected orphan types also cleaned in this change

**Comment by AdamAdHocTeam** [comment]
> Please write JIRAs for the two unexpected orphan types also cleaned in this change
we created:
[TTAHUB-1638](https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1638)

**Comment by thewatermethod** [comment]
👍 The SQL looks great... thanks for the neatness/comments there, I was able to follow it easily

I ran into these scenarios when I was testing:

Scenario 1
- Create a new report w/ 1 recipient
- Create a new goal
- Submit report
- As approver, edit report, deleting goal
- Approve report. Goal exists, is on RTR, etc

Scenario 2
- Create a new report w/ 1 recipient
- Create a new goal
- Submit report
- As different user approver, mark as needs action
- back to creator, edit report, deleting goal
- Approve report as other user. Goal exists, is on RTR, etc

**Review by thewatermethod — APPROVED** [review]

**Pull request merged**
