### PR TITLE
fix error on save when clearing date

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

A report will no longer try to save invalid dates to the database

## How to test
- Start creating a new AR
- Enter the start and end date
- Clear the start date
- Note a validation error "Please enter a valid date" is showing
- Save draft
- Note the report was successfully saved

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-677

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by jasalisbury** [comment]
I still get `2022-02-28 22:04:35.920 UTC [278] ERROR:  invalid input syntax for type date: "Invalid date"` when I follow the steps for a brand new activity report. If the report has been saved I can remove the start date and "save" (although it just uses the previously saved date, it doesn't set the date as "blank")

**Comment by kryswisnaskas** [comment]
The change seemed to have eliminated the error on a new report 👍 
I do still see the error on updating an existing report, e.g.
- create a new report
- enter a date
- save
- clear date
- save (error shows)

**Comment by kryswisnaskas** [comment]
This change fixes the scenario above. Could we also check for other invalid dates in this PR?
e.g. '02/343' or 'random string' ?

At some point, it would be good to implement a way to prevent users from entering invalid date characters, but that could be for another ticket.

**Review by jasalisbury — APPROVED** [review]

**Review by kryswisnaskas — APPROVED** [review]
Looks good!

**Pull request merged**
