### PR TITLE
Update node version to one supported by cloud.gov

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

Exactly what it says on the tin

## How to test

CI passes

## Issue(s)

There's no ticket for this

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by AdamAdHocTeam — APPROVED** [review]
LGTM!

**Review by GarrettEHill — APPROVED** [review]

**Comment by GarrettEHill** [comment]
Could we add a test to monitor this for us?

`const axios = require('axios');
const cheerio = require('cheerio');

// Function to retrieve the HTML content of the release page
async function getReleasePageContent() {
  try {
    const response = await axios.get('https://github.com/cloudfoundry/nodejs-buildpack/releases');
    return response.data;
  } catch (error) {
    console.error('Error retrieving release page content:', error);
    throw error;
  }
}

// Function to parse the release page HTML and extract Docker image names
function parseReleasePage(html) {
  const $ = cheerio.load(html);

  // Find the first row of the table which contains the column headers
  const columnHeaderRow = $('table.release-timeline-table tbody tr').first();

  // Extract the column names from the first row
  const columnNames = [];
  columnHeaderRow.find('th').each((index, element) => {
    columnNames.push($(element).text().trim());
  });

  // Find the row that corresponds to the framework and version columns
  const frameworkIndex = columnNames.indexOf('Framework');
  const versionIndex = columnNames.indexOf('Version');
  const dataRows = $('table.release-timeline-table tbody tr').slice(1); // Exclude the first row (column headers)

  const dockerImages = [];

  // Extract the framework and version data from each row and construct the Docker image name
  dataRows.each((index, element) => {
    const framework = $(element).find('td').eq(frameworkIndex).text().trim();
    const version = $(element).find('td').eq(versionIndex).text().trim();
    const dockerImage = `cimg/${framework}:${version}-browsers`; // Include 'cimg/' prefix and '-browsers' suffix
    dockerImages.push(dockerImage);
  });

  return dockerImages;
}

// Jest test to verify if the Docker images referenced in the CircleCI configuration file are still available
describe('Docker image verification', () => {
  test('Docker images referenced in .circleci/config.yaml should be available in the latest release', async () => {
    const releasePageContent = await getReleasePageContent();
    const dockerImages = parseReleasePage(releasePageContent);

    // Read .circleci/config.yaml and extract the Docker image references
    const circleCIConfig = require('.circleci/config.yaml');
    const dockerImageReferences = circleCIConfig.jobs.map(job => job.docker);

    // Verify if the Docker image references are available in the latest release
    dockerImageReferences.forEach(dockerImageRef => {
      expect(dockerImages).toContain(dockerImageRef);
    });
  });
});
`

**Comment by thewatermethod** [comment]
@GarrettEHill I’m not opposed if you think it’s worthwhile  - but it might not be worth the effort as 1) we get an email the day before 2) if I understand correctly, this test would only fail at the exact time the CI started failing, so it would functionally be the same as the message we get from the CI.

**Comment by thewatermethod** [comment]
@GarrettEHill Also does Circle CI not have an API we can use for that instead of a scraper? Feels a little clunky.

**Pull request merged**
