### PR TITLE
Configure smtp host

### PR DESCRIPTION
**Pull request by kryswisnaskas**
## Description of change
Enables SMTP configuration. Fixes issues with directly accessing reports through links in the notifications.

NOTE - This is a prerequisite for the notifications being functional, but it needs to be deployed to prod once the ability to subscribe/unsubscribe is implemented.

## How to test
This is currently deployed to Sandbox. The server & the configuration can be tested there by adding a collaborator, approving a report, requesting changes, and submitting a report for approval.
https://tta-smarthub-sandbox.app.cloud.gov/

For example:
- create a report and choose yourself as the approver
- approve a report
- verify that you received a notification

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-756

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [x] Code is meaningfully tested
- [n/a] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [n/a] API Documentation updated
- [x] Boundary diagram updated
- [n/a] Logical Data Model updated
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by GarrettEHill — APPROVED** [review]

**Comment by thewatermethod** [comment]
Made a report, added myself as an approver and requested changes.
Never got an email and I'm seeing failed jobs in the queue when I look at the logs for sandbox in kibana

**Comment by kryswisnaskas** [comment]
Thanks. I'll take a look. How about adding yourself as a collaborator?

**Comment by thewatermethod** [comment]
Ah! Now that worked like a charm

**Review by jasalisbury — COMMENTED** [review]
I was able to get emails when I was added as a collaborator and when my report was approved. I didn't get one when I was added as an approver (not sure if I should have!)

**Review by jasalisbury — APPROVED** [review]

**Pull request merged**
