### PR TITLE
increase prod memory limit

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
- Production memory limit to 4GB
- Change Report Menu export limit to 12000 (exports larger than that will not be allowed in the UI

## How to test
- Identical memory limits & UI changes are on dev right now

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-471

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [n/a] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [n/a] API Documentation updated
- [n/a] Boundary diagram updated
- [n/a] Logical Data Model updated
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by jasalisbury — APPROVED** [review]
Works in dev! Do you know how close we are to OOMing at 12k reports? We almost have 11k reports total in dev, so I assume we are already over 12k in prod.

**Comment by thewatermethod** [comment]
> Do you know how close we are to OOMing at 12k reports?

I do not! My testing strategy so far has been click the button and see if the site goes down. Maybe there's some New Relic thing that could help with that?

**Comment by jasalisbury** [comment]
> > Do you know how close we are to OOMing at 12k reports?
> 
> I do not! My testing strategy so far has been click the button and see if the site goes down. Maybe there's some New Relic thing that could help with that?


From [new relic](https://one.newrelic.com/launcher/dashboards.launcher?platform[accountId]=3062577&platform[$isFallbackTimeRange]=false&pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmRldGFpbCIsInVzZURlZmF1bHRUaW1lUmFuZ2UiOmZhbHNlLCJzZWxlY3RlZFBhZ2UiOiJNekEyTWpVM04zeFdTVnA4UkVGVFNFSlBRVkpFZkRFM05ERXpORGciLCJpc1RlbXBsYXRlRW1wdHkiOmZhbHNlLCJlbnRpdHlHdWlkIjoiTXpBMk1qVTNOM3hXU1ZwOFJFRlRTRUpQUVZKRWZERTNOREV6TkRnIn0=&overlay=eyJuZXJkbGV0SWQiOiJkYXRhLWV4cGxvcmF0aW9uLnF1ZXJ5LWJ1aWxkZXIiLCJpbml0aWFsQWN0aXZlSW50ZXJmYWNlIjoibnJxbEVkaXRvciIsImluaXRpYWxRdWVyaWVzIjpbeyJhY2NvdW50SWQiOjMwNjI1NzcsIm5ycWwiOiJTRUxFQ1QgbWF4KGFwbS5zZXJ2aWNlLm1lbW9yeS5waHlzaWNhbCkgQVMgJ01lbW9yeSBVc2VkIChNQiknIEZST00gTWV0cmljIFdIRVJFIGFwcE5hbWUgPSAndHRhLXNtYXJ0aHViLWRldicgVElNRVNFUklFUyBTSU5DRSAyNTkyMDAgc2Vjb25kcyBhZ28ifV0sImluaXRpYWxDaGFydFR5cGUiOiJsaW5lIiwiZWRpdE1vZGUiOiJWSUVXIiwiaW5pdGlhbE5ycWxWYWx1ZSI6IiIsImluaXRpYWxBY2NvdW50SWQiOjMwNjI1NzcsImluaXRpYWxDaGFydFNldHRpbmdzIjp7ImNoYXJ0VHlwZSI6IkNIQVJUX0xJTkUiLCJsaW1pdCI6MjE3Ljk0OTM5OTgyMDk2MzU1LCJsaW5rZWRFbnRpdHlHdWlkIjpudWxsLCJsaW5rZWREYXNoYm9hcmRJZCI6bnVsbH19&state=8695f784-bd72-c865-a9cb-b3bf5987897b) (Hopefully the link takes you to the graph!)
Screenshot from 2021-11-19 09-20-11

Looks like dev peaks out at 2100ish MB. So it _seems_ like we have some wiggle room? We may want to keep the limit at 12k just so we keep the wiggle room.

**Comment by thewatermethod** [comment]
Totally agree, from discussions sounds like most users will only want around 4-5k max at a time, and some wiggle room will probably be needed in case the exports need to grow.

**Comment by jasalisbury** [comment]
> Totally agree, from discussions sounds like most users will only want around 4-5k max at a time, and some wiggle room will probably be needed in case the exports need to grow.

I will say it would be nice to know what downloading an additional 12k reports (so 24k total) does to the max memory. I would assume max memory would also double but maybe it doesn't? It would be nice to have a way of generating a lot of report data, could help us forecast where we will see performance issues in the future. I think we already have a load testing ticket, maybe we should move the priority on it up a bit?

Anyways if most users are downloading 4-5k I think the current limit is fine!

**Comment by thewatermethod** [comment]
> I will say it would be nice to know what downloading an additional 12k reports (so 24k total) does to the max memory.

👍 

[this guy](https://ocio-jira.acf.hhs.gov/browse/TTAHUB-203)? 

Think we need to specifically note that we should test 24k report exports in there?

**Comment by jasalisbury** [comment]
> > I will say it would be nice to know what downloading an additional 12k reports (so 24k total) does to the max memory.
> 
> +1
> 
> [this guy](https://ocio-jira.acf.hhs.gov/browse/TTAHUB-203)?
> 
> Think we need to specifically note that we should test 24k report exports in there?

Good call, I just updated the description of the ticket.

**Pull request merged**
