### PR TITLE
[TTAHUB-1120] fix for spacing and display accordion

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
This fix handles the spacing issue relayed in the ticket (although it looked as though it had been partially fixed already), as well as fixing a related bug where the wrong form field was accessed by the ReviewItem component

## How to test
View the review page and confirm  that the spacing is correct and that the goals & objectives section is populated with data, even if you've opened a goal for editing.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1120

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by kryswisnaskas** [comment]
Looks nice! - I verified that the review section shows the goals even if one of them is being edited.

But, I did find a couple of things while looking at it. 
Having 2 goals on a report (created by running the Playwright test), I was able to mistakenly attribute resources from goal 1 to goal 2.
Steps:
- run Playwright test that creates a report with 2 goals g1 and g2 
- g1 has a resource link while g2 doesn't
- navigate to the "Goals and Objectives" section
- both goals are read-only
- edit g1
- g1 is now open in the edit mode
- edit g2
- g1 is now read-only and g2 is in the edit mode
- click "Save draft"
- navigate to the "Review" section
- both goals show nicely there, but g2 now has a resource link

Another minor issue I saw was that the above report's "Goals and Objectives" section would ocassionaly show as "Not Started" even though both goals were already there (I was navigating between the "Goals and Objectives" and the "Review")

**Comment by thewatermethod** [comment]
>  both goals show nicely there, but g2 now has a resource link

@kryswisnaskas - I was able to reproduce this on staging (where this PR hasn't been merged). Really, this PR only changes which field in the form data is displayed on the review page. 

Likewise, this PR doesn't fix the bug with the navigation, which you reported on the previous PR - I know I still need to log this as a bug, I have 4 notes on my desk about Jiras I need to write, which I was planning on doing tomorrow.

I agree that we should treat both issues as bugs to be fixed sooner rather than later but I would hate to hold up this PR on issues that weren't caused by it.

**Comment by kryswisnaskas** [comment]
Sounds good, thanks!

**Review by kryswisnaskas — APPROVED** [review]

**Comment by thewatermethod** [comment]
Ticket for fixing the side navigation interaction: https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1312

**Pull request merged**
