### PR TITLE
Add GA to the boundary diagram

### PR DESCRIPTION
**Pull request by kryswisnaskas**
## Description of change
Modified the boundary diagram to add Google Analytics.

## How to test
Look at the new diagram

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-0

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [n/a] Code is meaningfully tested
- [n/a] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [n/a] API Documentation updated
- [n/a] Boundary diagram updated
- [n/a] Logical Data Model updated
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by thewatermethod — APPROVED** [review]
I have looked at the new diagram - Google Analytics is on there

**Comment by GarrettEHill** [comment]
The diagram needs to have Google Analytics connected to the "Smart Hub User" as it all runs client side.

**Review by hardwarehuman — APPROVED** [review]
LGTM

**Review by jasalisbury — APPROVED** [review]
:shipit:

**Pull request merged**
