### PR TITLE
[TTAHUB-1102] Fix OE Objective Status Saving

### PR DESCRIPTION
**Pull request by AdamAdHocTeam**
## Description of change

The status of an objective is not saving.

## How to test

Create an OE report and add an objective with the status 'Suspended'. Approve the report and verify in the 'Approved' view it shows as suspended.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1102

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [x] Update JIRA ticket status

### CODE REVIEW

**Comment by kryswisnaskas** [comment]
🤔 On this branch I am unable to save goal with a "Suspended" status

**Comment by AdamAdHocTeam** [comment]
> 🤔 On this branch I am unable to save an objective with a "Suspended" status

What steps are you taking?

**Review by AdamAdHocTeam — COMMENTED** [review]
@kryswisnaskas this is now fixed.

**Comment by kryswisnaskas** [comment]
Looks good! 👍 I can save the goal or report and the objective's status is saved on an activity report.

I still found that the Suspended status doesn't show on the RTR page. Instead, it shows as "Needs Status"

Steps:
- create an AR for a recipient and add a new objective with a Suspended status
- submit and approve the report
- note on the RTR page that objective displays "Needs Status"

**Review by GarrettEHill — APPROVED** [review]

**Comment by AdamAdHocTeam** [comment]
> Looks good! 👍 I can save the goal or report and the objective's status is saved on an activity report for both a recipient and other entity.
> 
> I still found that the Suspended status doesn't show on the RTR page. Instead, it shows as "Needs Status"
> 
> Steps:
> 
> * create an AR for a recipient and add a new objective with a Suspended status
> * submit and approve the report
> * note on the RTR page that objective displays "Needs Status"

This has been fixed.

**Pull request merged**
