### PR TITLE
[TTAHUB-3022] Backup production DB on each deploy

### PR DESCRIPTION
**Pull request by GarrettEHill**
## Description of change

Add step in circleci to auto-backup production as part of the deployment process, So that any failed deployment can be reverted back to a known good state.

## How to test
It runs the same DB backup function that the scheduled backup does, just as part of the production deployment job. Only the production deployment job.

## Issue(s)

* https://jira.acf.gov/browse/TTAHUB-3022

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Before merge to main

- [ ] OHS demo complete
- [ ] Ready to create production PR

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by kcirtapfromspace** [comment]
What is the retention (policy) around backups? 

is it like 30 days 1 in 1 out?

**Comment by GarrettEHill** [comment]
@kcirtapfromspace  We currently do not have a deletion schedule. A JIRA should be made for that

**Review by hardwarehuman — APPROVED** [review]
I think a YAML comment to note that there's currently no backup management might be good, but I'm also not really sure where we would put that. But I would want something in there to note that all of this was written assuming that we would fix this eventually and is thus currently a time bomb with a long and mostly predictable fuze. Maybe just creating the Jira is all we should really because commenting it is basically burying a postit note.

**Review by thewatermethod — APPROVED** [review]
As part of the resolution of this ticket, we should (as suggested above) write a Jira to document the need for a backup management policy and add a section to the main README explaining the backups, both how to run them on demand and that they run each production deploy, and with a "Retention policy" subheading that says "TBD."

**Review by nvms — APPROVED** [review]
> So that any failed deployment can be reverted back to a known good state

We talked in Slack about improving our documentation around restoring these backups in the context of cloud.gov, the various ways to do it, etc. I don't think it needs to be a part of this PR, but something we should keep in mind. The process you outlined in the RDS upgrade you handled last week was pretty involved and not documented anywhere outside of that Slack post (as far as I can tell).

**Pull request merged**
