### PR TITLE
[TTAHUB-1688] Allow editing of FEI goals on the RTR

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
Several needed improvements to the conditional prompts/FEI goal feature. Most pertinently, the ability to edit an existing curated goal's prompts has been added to the RTR's edit goal form.

## How to test
- Create a multi-**recipient** report. Select the FEI goal, and approve the report. You should be unable to select FEI root causes for the goal, since it is a multi-recipient report.
- Create a second report, using one of the two previous recipients. Update the goal's FEI root cause, submit, and approve the report.
- Go to the RTR and the goals and objectives tab for the first recipient. You should see the FEI goal, and when you edit it, you'll see the root cause as read only.
- Go to the RTR and the goals and objectives tab for the second recipient. Since you've never added root causes via an activity report, you should be able to edit the root causes on this recipient's FEI goal. Ensure you can do so without issue.

## Issue(s)
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1688

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by kryswisnaskas** [comment]
Nice! In the most part it works as advertised, but I did run into an error:

- create a report with 2 recipients, submit and approve
- create a second report with the first of the above recipients
- select the FEI goal and 2 root causes
- "Save goal"
- edit the newly created goal
- note that there is no way to edit the root causes and "Save draft" produces: `Error(`Response for '${promptRequirements.title}' is required.`

**Comment by kryswisnaskas** [comment]
Looks good now with the fix! 🚀 

One outstanding question still and this is more of a business question. Did we decide that as soon as 2 root causes are entered and the goal saved, there is no way to edit the root causes?

This might become a source of frustraction in a case when someone just made a mistake and wants to correct it before going any further. Since it's no longer editable the user might try removing the goal and re-selecting it. In this case they might lose the tta, but not being able to edit the root causes anyway. They might also try deleting the activity report thinking that starting from scratch would make a difference (but it doesn't).

**Comment by thewatermethod** [comment]
> One outstanding question still and this is more of a business question. Did we decide that as soon as 2 root causes are entered and the goal saved, there is no way to edit the root causes?

We did, since the goal is on an approved report (I originally demoed this with the ability to perpetually change the root causes and was told to adjust)

**Comment by kryswisnaskas** [comment]
> st)

Then emphasizing the importance of user guidance makes sense. Maybe we can remind everyone. Users will understand that once the "Save goal" button is pressed, the root causes are locked.

**Review by kryswisnaskas — APPROVED** [review]

**Comment by thewatermethod** [comment]
> Then emphasizing the importance of user guidance makes sense. Maybe we can remind everyone. Users will understand that once the "Save goal" button is pressed, the root causes are locked.

I am meeting with Patrice to demo some other changes later today, I will confirm this is the expected behavior with her then

**Comment by thewatermethod** [comment]
>  I am meeting with Patrice to demo some other changes later today, I will confirm this is the expected behavior with her then

Confirmed that this is the expected behavior

**Pull request merged**
