### PR TITLE
[TTAHUB-1029] fix editing experience

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
- Changes to URL structure to make it more meaningful when editing multiple goals, updated edit menu to use this new structure. Visual changes to the goal form to make the fact that multiple goals are being edited more obvious (Goal X, Y now shows in the title)
- New hook to read URL parameters into state
- Fix roll up logic on the create goals form and the RTR so that the data across all the goals and objectives is displayed
- Also had to create logic to roll up other entity goals

## How to test
Create a multi-grant single recipient goal. Edit it from the RTR table. Use it on an approved AR. Check the RTR again, make sure that you can still edit it and that the info is properly displayed in the table.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1029

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by AdamAdHocTeam — COMMENTED** [review]
Using a goal from RTR on an report (not approved) has blank AR field on RTR.

image

Let me know if it needs to be approved.

**Review by AdamAdHocTeam — COMMENTED** [review]
Something to try to reproduce: 

1. Create a multi grant goal.
2. Create two reports using this Goal and approve.
3. Go to RTR recipient page attempt to sort by 'Created On'.

I get the below map error on the UI but no server error.

image

Another way I get the same error is to edit recipient '**Hilpert Inc**' id **3**. Then go to the Goals and Objectives tab notice the map error in the console.

**Comment by thewatermethod** [comment]
> Let me know if it needs to be approved.

Yes, they have to be approved

**Comment by thewatermethod** [comment]
@AdamAdHocTeam I was able to reproduce and fix that error

**Comment by thewatermethod** [comment]
Should be fixed [on this PR](https://github.com/HHS/Head-Start-TTADP/pull/1104)

**Pull request merged**
