### PR TITLE
[TTAHUB-110][TTAHUB-146]: Filter and Report menus a11y improvements

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

Various changes to filter and report menus to improve a11y specifically as it relates to keyboard navigation and screen readers.

Both Filter and ReportMenu components were given "menu" roles for the menus. The Filter component was given the "toolbar" role since it is a collection of controls. Event handlers for keyUp events were added to close menus and move focus back to the button that opened the menu.

When filters are added using the Add Filter button, focus is moved to the new filter. Labels for the filter as a whole were adjusted for better readability.

"Phrases" were adjusted on the DateRangePicker so it wouldn't use the words "checkin" or "checkout" in reference to picking start and end dates.

Daniel created an AriaLiveRegion that is loaded in the DOM early on so we can have status-type messages read out to screen readers after interactions like applying filters. So when you apply a filter, a message like "1 filter applied" should be announced to the user.

Discussion around various expectations are on the ticket, TTAHUB-110.

## How to test

Use a screenreader such as VoiceOver on macOS to navigate to and into Filter and Report menus using the keyboard. For VoiceOver, the keyboard navigation involves using the VoiceOver modifier, e.g. Control-Option- to navigate a page. Note that tab navigation is not necessarily the same as screenreader navigation.

Create, apply, and remove various filters.

## Issue(s)

*  https://ocio-jira.acf.hhs.gov/browse/TTAHUB-110
*  https://ocio-jira.acf.hhs.gov/browse/TTAHUB-146

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] API Documentation updated

**Does not apply to this code (no changes to data model, architecture, etc)**
- [ ] ~Boundary diagram updated~ 
- [ ] ~Logical Data Model updated~
- [ ] ~[Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~ ~

### Production Deploy
*not a production deploy*
- [ ] Staging smoke test completed

### After merge/deploy
*no jira access*
- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by rahearn — CHANGES_REQUESTED** [review]
Nice work, voice announcements are clear and navigation mostly works perfectly.

I did run into one exception that needs to be fixed. Both with and without VoiceOver, the month forward and month back buttons cause the entire filter UI to close, making them unusable. Also, those buttons are announced by VoiceOver as just "button"

**Comment by thewatermethod** [comment]
Thanks! I see the issue with the month buttons

Hmm, could you clarify what you mean by it only announces "button"? For me (on Safari and Firefox) Voiceover is announcing the text in the aria-label attribute followed by button. (i.e. "Move forward to switch to the next month, button. You are on a button")

**Comment by rahearn** [comment]
> Could you clarify what you mean by it only announces "button"? For me (on Safari and Firefox) Voiceover is announcing the text in the aria-label attribute followed by button. (i.e. "Move forward to switch to the next month, button. You are on a button")

I could have sworn I was only betting "button" for those with voiceover and safari, but maybe I'm misremembering. If you're hearing the proper behavior then just need to prevent the filter UI from closing when they're used.

**Comment by PatricePascual-ACF** [comment]
@thewatermethod - Thanks for the demo! 
Could you add a note documenting why some items were left unchecked in the checklist?
(@kryswisnaskas, we'd like to do this moving forward.)
Then I'll merge.

**Comment by thewatermethod** [comment]
@PatricePascual-ACF Thanks! I updated the text of the pull request around the unchecked-checklist items.

**Comment by PatricePascual-ACF** [comment]
Thanks, @thewatermethod!

**Review by PatricePascual-ACF — APPROVED** [review]

**Pull request merged**
