### PR TITLE
[TTAHUB-2138] update-node-to-18.18.0

### PR DESCRIPTION
**Pull request by GarrettEHill**
## Description of change
Update node to buildpack supported version

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2138

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by GarrettEHill** [comment]
Local is throwing: 
```/node_modules/node-expat: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/xenitov/work/Documents/GitHub/Head-Start-TTADP/node_modules/node-expat
Output:
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'nopt'
Require stack:
- /usr/share/nodejs/node-gyp/lib/node-gyp.js
- /usr/share/nodejs/node-gyp/bin/node-gyp.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/share/nodejs/node-gyp/lib/node-gyp.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/node-gyp/lib/node-gyp.js',
    '/usr/share/nodejs/node-gyp/bin/node-gyp.js'
  ]```

CI is throwing:
```info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
error An unexpected error occurred: "/home/circleci/project/node_modules/chromedriver: Cannot read properties of undefined (reading 'getOption')".```

**Comment by GarrettEHill** [comment]
CI is throwing:
```info This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
error An unexpected error occurred: "/home/circleci/project/node_modules/chromedriver: Cannot read properties of undefined (reading 'getOption')".```

**Comment by thewatermethod** [comment]
@GarrettEHill as a first step, did you re-run yarn deps? It doesn’t look like the lockfiles have changed

**Comment by GarrettEHill** [comment]
> @GarrettEHill as a first step, did you re-run yarn deps? It doesn’t look like the lockfiles have changed

- nvm install 18.18.0
- yarn or yarn deps fails

**Comment by thewatermethod** [comment]
This is a bit of a stumper

**Comment by thewatermethod** [comment]
I don't believe we need Chromedriver anymore so I removed some packages and updated a few others and attempted a reinstall, locally. I get a similar error:
 
Screenshot 2023-09-28 at 9 26 26 AM

I'm not sure what is looking for node-gyp, I believe it's a package node uses to run non-JavaScript code. In the past I've seen errors related to it, but generally it means that the bindings generated on one machine don't match (a windows Python environment on a Unix machine, for example). I could be wrong about what it does. I also don't understand how that could happen in a docker-based environment, or on install.

**Comment by thewatermethod** [comment]
perhaps removing the lockfiles before installing would make a difference, i.e. could the registry link be pointed to the wrong tarball or something?

**Comment by GarrettEHill** [comment]
@kcirtapfromspace can you look at this

**Comment by thewatermethod** [comment]
Closed in favor of #1771

**Pull request closed without merging**
