### PR TITLE
[TTAHUB-1243] dedupe objectives

### PR DESCRIPTION
**Pull request by GarrettEHill**
## Description of change
Some objectives are duplicates with the only difference being white space, this migration will resolve the duplicates.

## How to test
No functional test, DB will nolonger have duplicate objectives for the same goal with the only delta being white space.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1243

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by hardwarehuman** [comment]
@GarrettEHill The obvious bugs are fixed and this is ready for you to review

**Comment by hardwarehuman** [comment]
Outcome on Dec 16th db:
```
 deleted_aros                 |    11
 migrated_objective_files     |    16
 deleted_objective_resources  |     3
 deleted_objective_topics     |    15
 deleted_objective_files      |     3
 migrated_aros                |   394
 updated_objectives           |   355
 migrated_objective_resources |    40
 deleted_objectives           |   381
 migrated_objective_topics    |   166
 ```

**Review by AdamAdHocTeam — COMMENTED** [review]
Looks like tests failing here still. I assume its not ready for review?

**Review by AdamAdHocTeam — COMMENTED** [review]
Does this script also remove leading and trailing white spaces?

**Comment by hardwarehuman** [comment]
@AdamAdHocTeam The script actually did trim whitespace, but after Garrett and I talked this over we realized that some leading whitespace is actually necessary for some things like bulleted lists. So, I just removed setting with trimmed titles. We still _match_ using trimmed titles, but the title will remain the untrimmed version of the "inheriting" member of a duplicate set.

I do think we should consider a migration to trim trailing whitespace and also trim on objective creation, but as a separate effort to be discussed so everyone agrees that's what we should do.

**Comment by GarrettEHill** [comment]
@AdamAdHocTeam @thewatermethod @nvms @kryswisnaskas
Because I started this, but Nathan took it over neither of us can/should be the approver. Can one of you review and approve?

**Comment by thewatermethod** [comment]
> that some leading whitespace is actually necessary for some things like bulleted lists

@hardwarehuman, not sure I understand what is meant by this... aren't the bulleted lists stored as HTML strings in the DB? I must be missing something obvious 😄 

@GarrettEHill -> as far as reviewing today, with no test provided I would have to puzzle through the SQL, which just takes me too long to do to start at 4:50 on a Friday... happy to take a crack at it on Monday though

**Comment by hardwarehuman** [comment]
@AdamAdHocTeam The titles are just plaintext, with things like tabs and literal UTF-8 bullet point characters (E2 80 A2) in them, so bulleted lists, introductory paragraph indentations and so on are taken straight without HTML formatting.

**Comment by AdamAdHocTeam** [comment]
> @AdamAdHocTeam The titles are just plaintext, with things like tabs and literal UTF-8 bullet point characters (E2 80 A2) in them, so bulleted lists, introductory paragraph indentations and so on are taken straight without HTML formatting.

What about excluding rows that have bullet points?

**Comment by GarrettEHill** [comment]
Why, they could have duplicates too

**Review by thewatermethod — APPROVED** [review]
Seems like a good way to start cleaning this stuff up. I do think we will need a follow-on PR to continuously handle the trimming as @hardwarehuman alludes to, as this does not entirely address some of the bugs we are seeing with duplicate info in the interface, copy + pasting, etc.

I do think we need to think about how we are storing these titles - if users are entering rich text/formatted text in these fields, it might make sense for the users to enter it and for us to store it as we do the TTA provided, which would complicate the matching conversation a bit.

**Pull request merged**
