### PR TITLE
[TTAHUB-2530] Remove fields from objective form in RTR

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
- Removed topics, resources, support type, objective status, courses, and files from RTR
- The "view goal" from the RTR is a little different, so I created a new template to stop the logic loops inside the create form from getting even crazier. To do that and keep things consistent, some bits of display were moved into reusable components
- Cleaned up the route on the backend for this page. We no longer care about "ObjectiveTopics", "ObectiveResources", etc, only their "ActivityReportObjectivesTopics" and the like counterparts. Moved it to Typescript to make refactors a little easier in the future.
- Removed an unused route on the backend
- Note that other PRs within this sprint will build on this work, altering the AR fields and cleaning up the database schema to remove unused tables.

## How to test
- Create a new goal on the RTR, with an objective. Confirm that the  topics, resources, support type, objective status, courses, and files fields aren't there.
- Edit that goal. If the objective isn't used on an activity report, the text should still be editable.
- Use that goal and objective on a report. Once the objective is on a report, the text is no longer editable.
- Approve the report and close the goal. Go the RTR and confirm that the view option is present. View the goal and confirm that it matches the design.
- Test the same cases with FEI goals and multirecipient reports.

## Issue(s)

* https://jira.acf.gov/browse/TTAHUB-2530

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Before merge to main

- [ ] OHS demo complete
- [ ] Ready to create production PR

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by AdamAdHocTeam — COMMENTED** [review]
One thing that I noticed one the goal was on the approved report using 1 of 2 objectives the goal source was still editable (same with unused objective text).

**Review by AdamAdHocTeam — COMMENTED** [review]
Another issue I came across that I couldn't reproduce on latest. Create a goal from RTR put it on a report with one recipient and complete the goals page (on the AR). Leave the AR then come back add one additional recipient. Go to the goals page notice it has lost the goal but if you select the same goal as before it auto populates with the pervious info.

**Comment by thewatermethod** [comment]
@AdamAdHocTeam 

> One thing that I noticed one the goal was on the approved report using 1 of 2 objectives the goal source was still editable (same with unused objective text).

This PR does not change the goal source. I have a second PR that updates the goal source. Objectives are editable from the RTR until they are on a report.

> Another issue I came across that I couldn't reproduce on latest. Create a goal from RTR put it on a report with one recipient and complete the goals page (on the AR). Leave the AR then come back add one additional recipient. Go to the goals page notice it has lost the goal but if you select the same goal as before it auto populates with the pervious info.

I am unable to reproduce this (see video):

https://github.com/HHS/Head-Start-TTADP/assets/3288586/86684251-d6e1-4c1f-9613-bdfa80c06bc1

What am I doing differently?

**Review by AdamAdHocTeam — APPROVED** [review]
Ok you I wasn't able to reproduce the issue this morning.

Looks good, nice to see we are removing some code.

**Review by GarrettEHill — APPROVED** [review]

**Pull request merged**
