### PR TITLE
[TTAHUB-3144] Fix transactionWrapper

### PR DESCRIPTION
**Pull request by nvms**
## Description of change

We weren't awaiting the result of the call to `sequelize.transaction` in `transactionWrapper`, so we couldn't catch when it threw.

## Issue(s)

* https://jira.acf.gov/browse/TTAHUB-3144

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Before merge to main

- [ ] OHS demo complete
- [ ] Ready to create production PR

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by thewatermethod** [comment]
I think Garrett has this same fix on #2233 ?

**Comment by nvms** [comment]
> I think Garrett has this same fix on #2233 ?

Yeah, I wanted to make sure he knew about it since he's working on stuff related to this in that PR.

Should we just wait for his to get merged, and scrap this?

**Review by GarrettEHill — APPROVED** [review]
Same as my PR...looks good

**Comment by thewatermethod** [comment]
See this w/ the stringify

```
SERVICE:ACTIVITY_REPORTS - Unexpected error in catch block - TypeError: Cannot read properties of undefined (reading 'length') {}
```

**Pull request merged**
