### PR TITLE
[TTAHUB-1005] Fix objective file uploader not handling multiple file uploads

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

Refactor the refactor; since we needed to heavily rewrite the file uploader to conditionally create an objective, we introduced bugs to make uploading multiple files fail or create multiple extra goals and objectives

## How to test

File uploads on objectives (RTR and AR) should continue to work with single files and now work for uploading multiple files.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1005

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by AdamAdHocTeam — COMMENTED** [review]
Looks good.

If I create a Goal and Objective with attachments from the RTR. Then use this Goal and Objective on a AR should the attachments be automatically shown?

**Comment by thewatermethod** [comment]
> If I create a Goal and Objective with attachments from the RTR. Then use this Goal and Objective on a AR should the attachments be automatically shown?

Yeah, should be

**Comment by thewatermethod** [comment]
> >    If I create a Goal and Objective with attachments from the RTR. Then use this Goal and Objective on a AR should the attachments be automatically shown?

> Yeah, should be

And now... they are

**Review by AdamAdHocTeam — COMMENTED** [review]
Found a bug: 
1. From RTR create a new goal. 
2. Add the first objective with two attachments.
3. Add a second objective with one attachment.
4. Remove the second attachment from the first objective.
5. Save

Notice that the attachment that was removed is still there in the read only view.

**Comment by thewatermethod** [comment]
> Found a bug

@AdamAdHocTeam [I have resolved this](https://github.com/HHS/Head-Start-TTADP/pull/1033/commits/7f8d15bd1e2ccaec31727ff19e29421497aba9b3)

**Review by AdamAdHocTeam — COMMENTED** [review]
Possible bug:

1. From RTR create a goal
2. Create two Objectives each with attachments
3. Use the goal on an AR add both Objectives.

Notice that when you add the second objective its missing the pre selected attachments.

**Comment by AdamAdHocTeam** [comment]
> Possible bug:
> 
> 1. From RTR create a goal
> 2. Create two Objectives each with attachments
> 3. Use the goal on an AR add both Objectives.
> 
> Notice that when you add the second objective its missing the pre selected attachments.

Also seems like even if you select the second objective it takes the files from the first one.

**Review by AdamAdHocTeam — APPROVED** [review]
My issues have been fixed.

:fire:

**Pull request merged**
