### PR TITLE
[TTAHUB-1085] Update form state when saving draft on goals and objectives page

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
This PR fixes the bugs below.

## How to test

**Data lingers in the local storage. Some data stays in the local storage and gives the users an incorrect view of what is in the database (Krys)**

Steps to see one case:

    create a new AR (I tried with 2 recipients)

    select an existing goal and click "Save Draft"
    navigate away from the page through the navigator
    come back and remove the goal
    select a different existing goal and use "Save Draft"
    reload the page
    observe that the old removed goal shows instead of the new one.

**Newly refreshed goal disappears when a page is refreshed. (Krys - this might be related to the above)**

Steps:

    create an AR (I used 2 different recipients)
    select an existing goal and click "Save Draft"
    refresh the page to see the goal disappear

**Navigating away from the "Goals and Objectives" section on an AR doesn't save data. (Krys)**

Steps:

    create a goal on a new AR
    without pressing "Save Draft", navigate away by selecting a different section, e.g. "Next Steps"
    come back to the "Goals & Objectives". 
    note no goals show

**Editing a newly imported goal on the RTR page changes the "createdVia"**

To simulate this scenario:

    find a goal that was imported from the RTTAPA that doesn't have an end date (if unable to find, change the "createdVia" and "isFromSmartsheetTtaPlan" in the db for any goal without the end date to simulate an imported goal)

    add an end date to the goal on the RTR page
    in the db, the "createdVia" will now be "rtr" and the "isFromSmartsheetTtaPlan" flag false

**Imported goals that don't have status are missing from the goal selection dropdown on an AR**

Steps:

    find a goal that was imported from the RTTAPA with a blank status
    create an activity report and try adding that goal to it
    the goal will not appear on the dropdown
    change the goal's status to "In Progress"
    the goal is now present in the dropdown on the AR dropdown.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1085

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by kryswisnaskas** [comment]
Looks like the above 3 problems are fixed! 🎉 

I did find this issue that seems related:
- create a new AR with 2 recipients
- select an existing goal and navigate away
- come back to Goals and Objectives
- select another existing goal and navigate away
- come back to Goals and Objectives
- 2 goals are showing as expected
- choose "Edit" from the top goal
- click "Save Draft"
- refresh the page
- only 1 goal is now displayed and it is not editable


I also found couple of other issues. I'll document them in the bug.

**Comment by thewatermethod** [comment]
> I did find this issue that seems related:
>  ...
> I also found couple of other issues. I'll document them in the bug.

@kryswisnaskas - the other issue you discovered, as well as the two additional ones you added to the Jira are solved by this PR now. I added a related comment to your PR for the import script as well.

**Comment by nvms** [comment]
> * create a new AR with 2 recipients
> * select an existing goal and navigate away
> * come back to Goals and Objectives
> * select another existing goal and navigate away
> * come back to Goals and Objectives
> * 2 goals are showing as expected
> * choose "Edit" from the top goal
> * click "Save Draft"
> * refresh the page
> * only 1 goal is now displayed and it is not editable

while attempting to reproduce this, I get stuck here:

> * 2 goals are showing as expected

when I come back to Goals and Objectives, I don't see any goals shown. is it expected that I should see two?

**Comment by thewatermethod** [comment]
> on the Goals and Objectives stage I select an existing goal from the "Select recipient's goal" dropdown, do absolutely nothing else, and **then navigate away from the page**. when I return to the AR, the goal I previously selected is no longer shown. this behavior doesn't surprise me because I didn't populate the remaining required form field (objective) before abandoning the form entirely

Just to double check: If you are navigating to another section of the AR, and returning to another section of the AR, then what I'm seeing is both goals in their little read-only boxes. Hopefully that's what you are seeing too. If you are leaving the AR form entirely, then nothing is saved and what you describe is expected.

**Review by nvms — APPROVED** [review]
> Hopefully that's what you are seeing too

oh whoops, yeah, I was completely navigating away from the AR :facepalm: thank you for clearing that up

looks good

**Pull request merged**
