### PR TITLE
New pre commit hook

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

This hook checks to see if common/src/index.js was updated, and if so, won't commit unless both yarn.locks and the package.json for common is also updated. As with all pre-commit hooks, we have to **install** the file for it do to anything 😄 .

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by GarrettEHill** [comment]
why did this get closed?

**Review by nvms — COMMENTED** [review]
@GarrettEHill I think this is less critical now that we've published the package, because as @thewatermethod said, we treat `common` as any other npm package now

this hook still has some value though, and for that reason I'm fine with keeping it around

that said, I'm not sure this is working? in the video below, shouldn't this hook have prevented this commit since it only included a change to `packages/common/src/index.js`?

https://github.com/HHS/Head-Start-TTADP/assets/17074357/6cf409aa-3421-4d96-92da-a470ef2d7658

**Comment by nvms** [comment]
@thewatermethod other than it existing at `.githooks/pre-commit` and being executable, is there anything I need to do?

**Review by nvms — APPROVED** [review]
@thewatermethod thank you for clearing this up for me on slack. I hadn't moved it to `.git/hooks` 🤦 

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
yarn run v1.22.19
$ eslint --fix packages/common/src/index.js

/Users/jonpyers/Head-Start-TTADP/packages/common/src/index.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

✖ 1 problem (0 errors, 1 warning)

Done in 1.14s.
ERROR: common/src/index.js was changed, but common/package.json was not updated. Please make sure to publish a new version.
```

**Pull request merged**
