### PR TITLE
[TTAHUB-417] Keyboard user improvements on Activity Reports table

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
Previously, if a keyboard user wanted to export selected reports, it would require **a lot** of tabbing if one of those reports were in the middle of the table.

Hidden tab stops were created directly after the selection checkbox. These are "aria-hidden" since a bunch of buttons with identical text would be confusing to screen-reader-only users, and they have additional navigational options.

## How to test
Select a report and tab through the document. Observe that you can tab to focus one of the hidden buttons (directly after the report checkbox) and hit enter to initiate a download of selected reports.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-417

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [n/a] API Documentation updated
- [n/a] Boundary diagram updated
- [n/a] Logical Data Model updated
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by jasalisbury — COMMENTED** [review]
Looks and works well! Have one question...

> Hidden tab stops were created directly after the selection checkbox. These are "aria-hidden" since a bunch of buttons with identical text would be confusing to screen-reader-only users, and they have additional navigational options.

Seems like having aria-hidden on a focus-able element might be an accessibility issue

> According to the fourth rule of ARIA, aria-hidden="true" should not be used on a focusable element. Additionally, since this attribute is inherited by an element's children, it should not be added onto the parent or ancestor of a focusable element. 

(from https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute)

If we want to go this route we will probably need to document why we think we can ignore the rule.

**Comment by thewatermethod** [comment]
Yeah, I'd be glad to (and definitely should) reach out to a specialist to confirm my thinking on that before we move forward. I could very well be wrong/there may be a better way. 

I just know that a common screen-reader usage pattern is using a shortcuts to list off all the buttons on a page (same for links, headings, etc). In that case, I would think that we wouldn't want 12 buttons that do the same thing with the same name being read off? But I wouldn't want to violate a core behavior either. Tough one.

> Adding aria-hidden="true" to an element removes that element and all of its children from the accessibility tree. This can improve the experience for assistive technology users by hiding ...duplicated content, such as repeated text

**Comment by thewatermethod** [comment]
Figured out an alternate way to that same solution that didn't involve aria-hidden.

As a sidenote, I think I might start a jira just to list off all the things we can change or update when we finally get to abandon IE11.

**Comment by jasalisbury** [comment]
> Figured out an alternate way to that same solution that didn't involve aria-hidden.

Cool I'll take a look!

> As a sidenote, I think I might start a jira just to list off all the things we can change or update when we finally get to abandon IE11.

Yeah we need to bring up IE11 end of life at our next standup, because it is coming up next year (thankfully!). We might get lucky and be able to drop support sooner. If I forget try to remember to add a sticky for it!

**Review by jasalisbury — APPROVED** [review]
:tada:

**Pull request merged**
