### PR TITLE
[TTAHUB-1094] [TTAHUB-1135] Program Specialist email notifications

### PR DESCRIPTION
**Pull request by nvms**
## Description of change

* The enum `enum_MailerLogs_action` was migrated to add two new fields: `granteeReportApproved` and `granteeReportApprovedDigest`.
* New email templates were added.
* The digest templates were updated to include new possible job name: `granteeReportApprovedDigest`.
* `granteeReportApprovedDigest` added to daily, weekly, monthly crons.
* `UserSettings` is migrated to include a new setting key: `emailWhenGranteeReportApprovedProgramSpecialist`
* The email preferences page now has an option for program specialists to receive emails when their grantee has an approved report.

Screen Shot 2022-12-06 at 12 56 35 PM

If an AR is approved which has more than one recipient where each share the same grant and program specialist (above), the subject of the email will include the names of each recipient:

Screen Shot 2022-12-06 at 12 57 01 PM

Screen Shot 2022-12-06 at 12 57 07 PM

(that AR display name above is a link now)

## How to test

*some unrelated tests were added to meet coverage threshold*

Create some known recipients on some known grants with yourself defined as the program specialist.

```sql
INSERT INTO "Recipients"
        ("id", "name", "createdAt", "updatedAt")
        VALUES (1010101, 'ABC Recipient', current_timestamp, current_timestamp);
INSERT INTO "Grants"
        ("id", "number", "recipientId", "regionId", "programSpecialistName", "programSpecialistEmail", "createdAt", "updatedAt", "status")
        VALUES (2020202, '123foobar456', 1010101, 1, 'Hello Specialist', 'jon.pyers@adhocteam.us', current_timestamp, current_timestamp, 'Active');
INSERT INTO "Recipients"
        ("id", "name", "createdAt", "updatedAt")
        VALUES (3030303, 'DEF Recipient', current_timestamp, current_timestamp);
INSERT INTO "Grants"
        ("id", "number", "recipientId", "regionId", "programSpecialistName", "programSpecialistEmail", "createdAt", "updatedAt", "status")
        VALUES (4040404, '123bazboo456', 3030303, 1, 'Hello Specialist', 'jon.pyers@adhocteam.us', current_timestamp, current_timestamp, 'Active');
```

Ensure your email is verified and you've opted into the new program-specialist-only email preference.

Create an AR and use those recipients, set yourself as the approver, and approve it. You should receive an email like the one shown above.

Additionally, ensure that the emails sent to you show up in the `MailerLogs` table.

The `down` migration should revert `enum_MailerLogs_action` to its original state, removing all mail logs that used the new enums.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1094
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1135

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by thewatermethod — APPROVED** [review]
Works as described! I did notice there might be something not getting passed into the mailer log (see the subject column and the undefined value)
Screen Shot 2022-12-09 at 4 25 16 PM
hat there

**Comment by nvms** [comment]
> Works as described! I did notice there might be something not getting passed into the mailer log (see the subject column and the undefined value)

Ah thanks for catching this!

**Comment by kryswisnaskas** [comment]
Thanks for creating the testing script! 

Comment on the variables names - if it's too late now, that's fine (I should have mentioned something earlier). Going forward though, could we use "recipient" instead of "grantee"?
A bit of a background on this - the recipients used to be "Grantees", but then OHS decided, the name would be "Recipients". We renamed references in the code from grantees to recipients. :)

**Comment by kryswisnaskas** [comment]
Overall, looks great! - verified that an email was received when subscribed and wasn't when wasn't. A MailerLog entry was created as expected. 👍

**Review by kryswisnaskas — APPROVED** [review]

**Comment by nvms** [comment]
> Thanks for creating the testing script!
> 
> Comment on the variables names - if it's too late now, that's fine (I should have mentioned something earlier). Going forward though, could we use "recipient" instead of "grantee"? A bit of a background on this - the recipients used to be "Grantees", but then OHS decided, the name would be "Recipients". We renamed references in the code from grantees to recipients. :)

not too late! I just renamed them all in 6afc755

**Pull request merged**
