### PR TITLE
[TTAHUB-1076] Show correct buttons on form when editing existing goals

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
- Editing an existing goal on the RTR now shows different buttons (save and cancel). Save simply saves and returns the user to the RTR, cancel does the same without saving first. 
- The tooltips on the Activity Reports table now open down if they are in the first five rows, the bottom five rows open in the top direction. This prevents tall tooltips being cut off at the top/bottom

## How to test
- Ensure the above works as expected

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1076

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by kryswisnaskas — COMMENTED** [review]
Verified that the buttons change now when editing "In Progress" and "Not Started" goals 👍 

Tooltip also looks good! 🎉 

Found a few things:
1. certain goals don't save. To reproduce:
- select RTR's first recipient in region one (Abbot, Ondricka & Bracus)
- edit goal G-61363
- click Save (note the error)

2. There is no space between "Region" and it's number on the goal edit form.
3. When attempting to edit a Closed goal, topic input field shows up as editable and required, but there are no buttons. Also, there is "Invaliddate" under date. (This might be a separate PR if it's too much since it is present on Dev as well)
4. We should prevent a scenario where someone with read permissions to multiple regions attempts to edit goals where they don't have write permissions in. We could bring this up at the standup.

**Comment by thewatermethod** [comment]
>  certain goals don't save. To reproduce:

I don't have that recipient in my local database. Is the error "Enter a valid date"? I would think if a user is opening up a goal to edit, they should have to fill out all the fields, even if the goal already existed (unless it's closed, etc)

**Comment by thewatermethod** [comment]
> We should prevent a scenario where someone with read permissions to multiple regions attempts to edit goals where they don't have write permissions in. We could bring this up at the standup.

We have a region id in the URL, I will open a separate PR to handle permissions on the frontend based on that.

> There is no space between "Region" and it's number on the goal edit form.
When attempting to edit a Closed goal, topic input field shows up as editable and required, but there are no buttons. Also, there is "Invaliddate" under date. (This might be a separate PR if it's too much since it is present on Dev as well)

These have been addressed. Just let me know if my understanding of the error in my previous comment is correct when you get a chance, @kryswisnaskas

**Comment by thewatermethod** [comment]
[This is the PR](https://github.com/HHS/Head-Start-TTADP/pull/1108) to handle the permissions more explicitly

**Comment by thewatermethod** [comment]
[This PR makes goal end date no longer a required field](https://github.com/HHS/Head-Start-TTADP/pull/1114)

**Review by AdamAdHocTeam — COMMENTED** [review]
This might have already been pointed out in Krys's review. If I edit and in progress goal add some topics and end date then save I get the below:

image

**Review by AdamAdHocTeam — APPROVED** [review]
Looks good.

**Pull request merged**
