### PR TITLE
[TTAHUB-1125] Default Select state should show placeholder

### PR DESCRIPTION
**Pull request by nvms**
## Description of change

The placeholder (- Select -) should always be shown when creating goals and objectives on the AR form.

Previously, for example, when creating a new objective, the default value was "Create a new objective".

## How to test

Create goals and objectives on the AR form and be sure the placeholder is always shown by default.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1125

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by AdamAdHocTeam — COMMENTED** [review]
Got a undefined key when saving two objectives on read only screen.

image

**Comment by nvms** [comment]
> Got a undefined key when saving two objectives on read only screen.
> 
> image

I see this on main as well as it seems the resources don't have the `key` property that we've been using for the key, so I just changed these to uuids in [7f30e26](https://github.com/HHS/Head-Start-TTADP/pull/1421/commits/7f30e26b761be15bebc468bb06c3cb0138576de9)

**Review by AdamAdHocTeam — COMMENTED** [review]
One thing I find odd about this whole change is that by default it says '- select -'.  But we also already allow the user to enter a new objective BEFORE selecting something from the drop down.

Shouldn't we hide the objective entry until the selection is made? I also don't see what's wrong with just having it default to create new objective. Especially if there are no other objectives to select from....

image

**Comment by thewatermethod** [comment]
Seeing some weirdness where you'd have to double select an objective to get the fields to show up

https://user-images.githubusercontent.com/3288586/227558536-b5994d59-0a43-4212-b333-412a6de0587f.mov

**Pull request closed without merging**
