### PR TITLE
[TTAHUB-581] Update certain topics on legacy reports

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

Expand existing script to account for topics that either were missed or absent from the previous jira. Move it to the "tools" folder and add a CLI script to run it

Note - I chose to do this the *dumbest* possible way. It would have maybe been possible, maybe even advisable, to first strip all the pipe + abbreviations out of topics first (like "| ECS"), but that also would have required an additional step and to have had to account for all the variations in those as well, and I personally felt that since I already had the code and the list of things to change, it was easy enough to just directly stick all the different variations in the dictionary for updating

## How to test

If you have local data, you can run the following sql to get a count of all the offending reports in your DB (mine, a semi-recent export for staging had ~2000)
```sql
SELECT "id", "topics" FROM "ActivityReports" AS "ActivityReport" 
WHERE "ActivityReport"."submissionStatus" != 'deleted' 
AND "ActivityReport"."topics" && 
ARRAY[
'Behavioral / Mental Health',
'QIP',
'CLASS: Classroom Management',
'Curriculum (Early Childhood or Parenting)',
'Environmental Health and Safety',
'Behavioral / Mental Health | HS',
'Behavioral / Mental Health | HS, FES',
'Child Assessment, Development, Screening | ECS',
'Curriculum/a  (Instructional or Parenting) | ECS, FES',
'Curriculum (Early Chidhood or Parenting)',
'Eligibility (ERSEA) | ECS, FES, GS',
'Environmental Health and Safety | HS',
'Facilities | GS','Family Support Services | FES',
'Fiscal / Budget | GS','Human Resources | GS',
'Leadership / Governance | GS, FES',
'Nutrition | HS','Oral Health | HS',
'Parent and Family Engagement | ECS, FES, HS',
'Partnerships and Community Engagement | ECS, FES, SS',
'Physical Health and Screenings | HS',
'Pregnancy | FES, HS',
'Program Planning, Operations, Management Systems | GS',
'Quality Improvement / QIP | GS',
'Safety Practices | HS',
'Transition Practices | ECS',
'Transition Practices | ECS, FES',
'Transportation | GS',
'parent/family engagement/program planning/QIP'
]::VARCHAR(255)[];
```
Then running the ```yarn updateTopicNames:local``` script should yield console output as to what changed, and you can re-run the SQL to verify you have nothing remaining. 

It would probably be helpful to double check my dictionary of changes against the original Jira. I've double checked it now but another set of eyes probably wouldn't hurt.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-581

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Comment by jasalisbury** [comment]
After running local on a recent copy of Prod I still get the following topics that aren't currently select-able

```
"Children with Disabilities | ECS"
"Coaching / Teaching / Instructional Support | ECS, FES"
"T/TA Planning"
"Corrective Actions | GS"
""Infant/Toddlers Preschool""
"Quality Improvement / QIP"
"Coaching / Teaching / Instructional Support | ECS"
"Other"
"CLASS / Learning Environments / Classroom Management | ECS"
```

Found with this query

```
select unnest(topics) from
	"ActivityReports" where "calculatedStatus" not in ('deleted', 'draft')
	AND "calculatedStatus" is not null and id not in (
		select id from "ActivityReports" where topics && ARRAY[
			'Behavioral / Mental Health / Trauma',
			'Child Assessment, Development, Screening',
			'CLASS: Classroom Organization',
			'CLASS: Emotional Support',
			'CLASS: Instructional Support',
			'Coaching',
			'Communication',
			'Community and Self-Assessment',
			'Culture & Language',
			'Curriculum (Instructional or Parenting)',
			'Data and Evaluation',
			'ERSEA',
			'Environmental Health and Safety / EPRR',
			'Equity',
			'Facilities',
			'Family Support Services',
			'Fiscal / Budget',
			'Five-Year Grant',
			'Home Visiting',
			'Human Resources',
			'Leadership / Governance',
			'Learning Environments',
			'Nutrition',
			'Oral Health',
			'Parent and Family Engagement',
			'Partnerships and Community Engagement',
			'Physical Health and Screenings',
			'Pregnancy Services / Expectant Families',
			'Program Planning and Services',
			'Quality Improvement Plan / QIP',
			'Recordkeeping and Reporting',
			'Safety Practices',
			'Staff Wellness',
			'Teaching Practices / Teacher-Child Interactions',
			'Technology and Information Systems',
			'Transition Practices',
			'Transportation'
		]::VARCHAR(256)[])
	group by unnest(topics)
```

**Comment by jasalisbury** [comment]
> Note - I chose to do this the _dumbest_ possible way. It would have maybe been possible, maybe even advisable, to first strip all the pipe + abbreviations out of topics first (like "| ECS"), but that also would have required an additional step and to have had to account for all the variations in those as well, and I personally felt that since I already had the code and the list of things to change, it was easy enough to just directly stick all the different variations in the dictionary for updating

I think this is fine! We already had the list of all topics that need to be updated and all the code was already in place to use it. Makes sense to do it the quick way since this is (hopefully!) the last time we'll need to use this script.

**Comment by thewatermethod** [comment]
> After running local on a recent copy of Prod I still get the following topics that aren't currently select-able

oh, my bad, I should have clarified in the pr text, but I replied in the jira about those topics looking for what to map those ones to (some of them don't really have clear analogues)

**Comment by jasalisbury** [comment]
We are still waiting on a few mappings correct?

**Review by jasalisbury — APPROVED** [review]
:rocket:

**Pull request merged**
