### PR TITLE
[TTAHUB-205] notify engineers in slack of daily scan failure

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

Uses circleci's slack orb to post a generic failure message in the acf-head-start-engineers channel should the daily scan job fail. The channel name and slack api key are stored in Circle CI in the contexts panel for HHS.

## How to test
I've created a slack channel (-mb-test-channel) and I've had the messages posted there. Let me know if you want to review and I'll add you to view the sample failure message that's been posted.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-205

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by jasalisbury — APPROVED** [review]
Is the message that gets posted a built in message somewhere? Do you know why there are "\n" characters before some of the text?

**Comment by thewatermethod** [comment]
> Is the message that gets posted a built in message somewhere? Do you know why there are "\n" characters before some of the text?

Yeah, this is the built in "event fail" on the circle ci slack orb 
https://circleci.com/developer/orbs/orb/circleci/slack#usage-notify_on_fail_with_template

I'm gonna check real quick to see if I can customize it a little more

**Comment by jasalisbury** [comment]
> Looks like the newlines are a known issue - we can customize only the "mentions" field, which I don't know if we want to do or not (send it to `@head-start-engineers` or w/e)
> 
> [CircleCI-Public/slack-orb#313](https://github.com/CircleCI-Public/slack-orb/pull/313)

I don't think it is that big of a deal that we need to put in a lot of effort to fix it, just wondering if it was something we could easily fix.

**Comment by kryswisnaskas** [comment]
Nice idea - it will additionally highlight how often these happen.

**Review by kryswisnaskas — APPROVED** [review]

**Pull request merged**
