### PR TITLE
[TTAHUB-945/954] Resolve create goals bugs reported by designers, rewrite file uploaders

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change

This change addresses [some feedback provided by the design team](https://ocio-jira.acf.hhs.gov/browse/TTAHUB-945) on the _create goals form_.

Specifically:
- Draft goals are now included on the RTR table page 
- The sort is adjusted to show draft goals first
- Button order, spacing, and an icon were all fixed to match the mockups

A large part of this PR is built to address a bug with the objective file uploader/RTR, where a file couldn't be uploaded until the objective was save, creating a confusing user interaction. The file upload functionality was broken out into two components, one for objectives and one for activity reports, and a new user interaction created 

## How to test
- Check that the feedback mentioned in Jira 945 has been resolved

Upload file functionality still works
- On an activity report, you can upload a supporting attachment and it is saved properly, and can be removed
- On an activity report, you can upload a file to an objective and it is saved properly, and can be removed
- On the RTR, you can upload a file to an objective and it is saved properly, and can be removed

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-945
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-954

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by AdamAdHocTeam — COMMENTED** [review]
Found a bug when creating a new AR. 

Adding a second attachment on the 'Supporting Attachments' page overwrites the previously added attachment.

**Comment by thewatermethod** [comment]
@AdamAdHocTeam I believe all these issues have been solved

**Comment by AdamAdHocTeam** [comment]
> @AdamAdHocTeam I believe all these issues have been solved

Looking now.

**Review by AdamAdHocTeam — COMMENTED** [review]
One thing I just thought about:
If a user adds attachments to a objective then clicks the 'no' radio button. Should we automatically remove the attachments?

Not sure if we want to address this here.

**Review by AdamAdHocTeam — APPROVED** [review]
You addressed all of my issues.

Probably want at least one other approver as there are a lot of changes here.

**Comment by thewatermethod** [comment]
> One thing I just thought about:
If a user adds attachments to a objective then clicks the 'no' radio button. Should we automatically remove the attachments?

I think we should be removing them when the objective is saved, I think a quick toggle shouldn't cause an objective to lose all it's files.

**Comment by AdamAdHocTeam** [comment]
> > One thing I just thought about:
> > If a user adds attachments to a objective then clicks the 'no' radio button. Should we automatically remove the attachments?
> 
> I think we should be removing them when the objective is saved, I think a quick toggle shouldn't cause an objective to lose all it's files.

Ok I think that makes sense if its how its working now.

**Pull request merged**
