### PR TITLE
[TTAHUB-2246] Export communication log

### PR DESCRIPTION
**Pull request by thewatermethod**
## Description of change
"export log" button on communication form

also changes from UI review:
- handle pagination/view of communication logs with zero pages
- add read-only creator name to form
- prevent navigation within form if there is no date
- set a max width for the form so it matches our other forms
- set a max width on the date column in the table so it isn't equal to the other cells

## How to test
Test that you can export logs
Test changes have been made

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2246

### Every PR

- [ ] Meets issue criteria
- [ ] JIRA ticket status updated
- [ ] Code is meaningfully tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] API Documentation updated
- [ ] Boundary diagram updated
- [ ] Logical Data Model updated
- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- [ ] UI review complete

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

### CODE REVIEW

**Review by AdamAdHocTeam — COMMENTED** [review]
Overall works great just two minor things.

**Comment by thewatermethod** [comment]
> Sort of odd if I am viewing the second page (12 total) and export I get out three records.
> Might need to add a key to the table.

@AdamAdHocTeam Good finds, these have been addressed

**Review by nvms — APPROVED** [review]
Works great.

Not sure how related it is to this PR, but I see new scopes in the diff for the "purpose" column, but I don't see a "purpose" filter in the UI - should I?

**Review by AdamAdHocTeam — APPROVED** [review]
Looks good. Issues are fixed.

**Comment by thewatermethod** [comment]
> Not sure how related it is to this PR, but I see new scopes in the diff for the "purpose" column, but I don't see a "purpose" filter in the UI - should I?

@nvms good eyes, but no, there is no purpose filter in the UI. This filter is used to filter the Communication logs on the RTTAPA updates table that you find in the RTR on the RTTAPA tab

**Pull request merged**
